"""reset old

Revision ID: 18b1a3d69e80
Revises: d98713d25e0f
Create Date: 2023-04-14 19:08:15.465971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18b1a3d69e80'
down_revision = 'd98713d25e0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.execute("CREATE TYPE role AS ENUM('admin', 'moderator', 'user')")
    op.add_column('users',
                  sa.Column('roles', sa.Enum('admin', 'moderator', 'user', name='role'), nullable=True, default='moderator'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'roles')
    op.execute("DROP TYPE role")
    # ### end Alembic commands ###
