"""'Init'

Revision ID: 4f84b5eb7471
Revises: 3237fbcf82f2
Create Date: 2023-04-01 19:52:15.223701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f84b5eb7471'
down_revision = '9eb91d9eb253'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contacts_additional_info_key', 'contacts', type_='unique')
    op.drop_index('ix_contacts_phone', table_name='contacts')
    op.create_index(op.f('ix_contacts_phone'), 'contacts', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contacts_phone'), table_name='contacts')
    op.create_index('ix_contacts_phone', 'contacts', ['phone'], unique=False)
    op.create_unique_constraint('contacts_additional_info_key', 'contacts', ['additional_info'])
    # ### end Alembic commands ###
