"""'Init'

Revision ID: e7654fda7dff
Revises: 4f84b5eb7471
Create Date: 2023-04-02 11:58:41.429577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7654fda7dff'
down_revision = '4f84b5eb7471'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contacts_phone', table_name='contacts')
    op.create_index(op.f('ix_contacts_phone'), 'contacts', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contacts_phone'), table_name='contacts')
    op.create_index('ix_contacts_phone', 'contacts', ['phone'], unique=False)
    # ### end Alembic commands ###
